/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CalcTaxes.java
 *
 * Created on 16 Φεβ 2011, 9:25:48 πμ
 */
package tools;

import components.MyDraggable;
import models.Receipt;
import org.jopendocument.util.PrintUtilities;
import receipts.Main;

/**
 *
 * @author ssoldatos
 */
public class CalcTaxes extends MyDraggable {

  private static final long serialVersionUID = 45757585L;
  private final double owner;
  private final double married;
  private float total;
  private double ownerNeeded;
  private String ownerNeededExpl;
  private double marriedNeeded;
  private String marriedNeededExpl;
  private double ownerRatio;
  private String ownerRatioExpl;
  private double marriedRatio;
  private String marriedRatioExpl;
  private double totalNeeded;
  private double ownerTax;
  private String ownerTaxExp;
  private double marriedTax;
  private String marriedTaxExp;
  private double totalTax;
  private String taxResult;
  private String totalForosResult;

  public CalcTaxes(double owner, double married) {
    Main.glassPane.activate(null);
    this.owner = owner;
    this.married = married;
    total = Receipt.getAmount("");
    if(married == 0){
      if(total > 15000){
        total = 15000;
      }
    } else {
      if(total > 30000){
        total = 30000;
      }
    }
    calculate();
    initComponents();
    setLocationRelativeTo(null);
    setVisible(true);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    panel = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    lb_foros = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    lb_totalForos = new javax.swing.JLabel();
    lb_totalEarn = new javax.swing.JLabel();
    lb_total_owner = new javax.swing.JLabel();
    lb_total_married = new javax.swing.JLabel();
    lb_totalEarn3 = new javax.swing.JLabel();
    lb_owner_needed = new javax.swing.JLabel();
    lb_owner_neededExp = new javax.swing.JLabel();
    lb_married_needed = new javax.swing.JLabel();
    lb_married_neededExp = new javax.swing.JLabel();
    lb_total_needed = new javax.swing.JLabel();
    lb_owner_ratio = new javax.swing.JLabel();
    lb_owner_ratioExp = new javax.swing.JLabel();
    lb_married_ratio = new javax.swing.JLabel();
    lb_married_ratioExp = new javax.swing.JLabel();
    lb_owner_tax = new javax.swing.JLabel();
    lb_owner_taxExp = new javax.swing.JLabel();
    lb_married_tax = new javax.swing.JLabel();
    lb_married_taxExp = new javax.swing.JLabel();
    lb_total_tax = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
    jButton1.setToolTipText("Κλείσιμο");
    jButton1.setBorder(null);
    jButton1.setBorderPainted(false);
    jButton1.setContentAreaFilled(false);
    jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton1.setFocusPainted(false);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer.png"))); // NOI18N
    jButton2.setToolTipText("Εκτύπωση");
    jButton2.setBorder(null);
    jButton2.setBorderPainted(false);
    jButton2.setContentAreaFilled(false);
    jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton2.setFocusPainted(false);
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    panel.setBackground(new java.awt.Color(255, 255, 255));
    panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText("Συνολικό εισόδημα :");

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel3.setText("Εισόδημα υπόχρεου :");

    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel4.setText("Εισόδημα συζύγου :");

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel5.setText("Συνολικό ποσό αποδείξεων :");

    jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getStyle() | java.awt.Font.BOLD));
    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel6.setText("Υπολογισμός απαιτούμενου ποσού αποδείξεων");

    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel7.setText("Υπόχρεου :");

    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel8.setText("Συζύγου :");

    jLabel9.setText("Συνολικό ποσό απαιτούμενων αποδείξεων :");

    jLabel10.setFont(jLabel10.getFont().deriveFont(jLabel10.getFont().getStyle() | java.awt.Font.BOLD));
    jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel10.setText("Επιμερισμός ποσού δηλωμένων αποδείξεων");

    jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel11.setText("Υπόχρεου :");

    jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel12.setText("Συζύγου :");

    lb_foros.setFont(lb_foros.getFont().deriveFont(lb_foros.getFont().getStyle() | java.awt.Font.BOLD));
    lb_foros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    lb_foros.setText(taxResult);

    jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel14.setText("Υπόχρεου :");

    jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel15.setText("Συζύγου :");

    lb_totalForos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lb_totalForos.setText(totalForosResult);

    lb_totalEarn.setFont(lb_totalEarn.getFont().deriveFont(lb_totalEarn.getFont().getStyle() | java.awt.Font.BOLD));
    lb_totalEarn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lb_totalEarn.setText(Helper.convertAmountForViewing(married+owner));

    lb_total_owner.setFont(lb_total_owner.getFont().deriveFont(lb_total_owner.getFont().getStyle() | java.awt.Font.BOLD));
    lb_total_owner.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lb_total_owner.setText(Helper.convertAmountForViewing(owner));

    lb_total_married.setFont(lb_total_married.getFont().deriveFont(lb_total_married.getFont().getStyle() | java.awt.Font.BOLD));
    lb_total_married.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lb_total_married.setText(Helper.convertAmountForViewing(married));

    lb_totalEarn3.setFont(lb_totalEarn3.getFont().deriveFont(lb_totalEarn3.getFont().getStyle() | java.awt.Font.BOLD));
    lb_totalEarn3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lb_totalEarn3.setText(Helper.convertAmountForViewing(total));

    lb_owner_needed.setFont(lb_owner_needed.getFont().deriveFont(lb_owner_needed.getFont().getStyle() | java.awt.Font.BOLD));
    lb_owner_needed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lb_owner_needed.setText(Helper.convertAmountForViewing(ownerNeeded));

    lb_owner_neededExp.setText(ownerNeededExpl);

    lb_married_needed.setFont(lb_married_needed.getFont().deriveFont(lb_married_needed.getFont().getStyle() | java.awt.Font.BOLD));
    lb_married_needed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lb_married_needed.setText(Helper.convertAmountForViewing(marriedNeeded));

    lb_married_neededExp.setText(marriedNeededExpl);

    lb_total_needed.setFont(lb_total_needed.getFont().deriveFont(lb_total_needed.getFont().getStyle() | java.awt.Font.BOLD));
    lb_total_needed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lb_total_needed.setText(Helper.convertAmountForViewing(totalNeeded));

    lb_owner_ratio.setFont(lb_owner_ratio.getFont().deriveFont(lb_owner_ratio.getFont().getStyle() | java.awt.Font.BOLD));
    lb_owner_ratio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lb_owner_ratio.setText(Helper.convertAmountForViewing(ownerRatio));

    lb_owner_ratioExp.setText(ownerRatioExpl);

    lb_married_ratio.setFont(lb_married_ratio.getFont().deriveFont(lb_married_ratio.getFont().getStyle() | java.awt.Font.BOLD));
    lb_married_ratio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lb_married_ratio.setText(Helper.convertAmountForViewing(marriedRatio));

    lb_married_ratioExp.setText(marriedRatioExpl);

    lb_owner_tax.setFont(lb_owner_tax.getFont().deriveFont(lb_owner_tax.getFont().getStyle() | java.awt.Font.BOLD));
    lb_owner_tax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lb_owner_tax.setText(Helper.convertAmountForViewing(ownerTax));

    lb_owner_taxExp.setText(ownerTaxExp);

    lb_married_tax.setFont(lb_married_tax.getFont().deriveFont(lb_married_tax.getFont().getStyle() | java.awt.Font.BOLD));
    lb_married_tax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lb_married_tax.setText(Helper.convertAmountForViewing(marriedTax));

    lb_married_taxExp.setText(marriedTaxExp);

    lb_total_tax.setFont(lb_total_tax.getFont().deriveFont(lb_total_tax.getFont().getStyle() | java.awt.Font.BOLD, lb_total_tax.getFont().getSize()+2));
    lb_total_tax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lb_total_tax.setText(Helper.convertAmountForViewing(totalTax));
    lb_total_tax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
    panel.setLayout(panelLayout);
    panelLayout.setHorizontalGroup(
      panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
        .addContainerGap(10, Short.MAX_VALUE)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(lb_totalEarn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(lb_total_married, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(lb_total_owner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(lb_totalEarn, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
        .addGap(395, 395, 395))
      .addGroup(panelLayout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addComponent(jLabel6)
        .addContainerGap(221, Short.MAX_VALUE))
      .addGroup(panelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lb_owner_needed, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(129, Short.MAX_VALUE))
      .addGroup(panelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lb_married_needed, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(395, 395, 395))
      .addGroup(panelLayout.createSequentialGroup()
        .addGap(197, 197, 197)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(lb_married_neededExp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(lb_owner_neededExp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
        .addContainerGap(15, Short.MAX_VALUE))
      .addGroup(panelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel9)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lb_total_needed, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(129, Short.MAX_VALUE))
      .addGroup(panelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        .addGap(395, 395, 395))
      .addGroup(panelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lb_owner_ratio, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(129, Short.MAX_VALUE))
      .addGroup(panelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lb_married_ratio, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(395, 395, 395))
      .addGroup(panelLayout.createSequentialGroup()
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
            .addGap(188, 188, 188)
            .addComponent(lb_married_ratioExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
            .addGap(185, 185, 185)
            .addComponent(lb_owner_ratioExp, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(panelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lb_foros, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(176, Short.MAX_VALUE))
      .addGroup(panelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelLayout.createSequentialGroup()
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lb_owner_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(119, 119, 119))
          .addGroup(panelLayout.createSequentialGroup()
            .addGap(162, 162, 162)
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(panelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lb_married_taxExp, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(panelLayout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_married_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(panelLayout.createSequentialGroup()
            .addComponent(lb_totalForos, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(lb_total_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(panelLayout.createSequentialGroup()
            .addGap(175, 175, 175)
            .addComponent(lb_owner_taxExp, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(272, 272, 272))
    );

    panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel12, jLabel14, jLabel2, jLabel3, jLabel4, jLabel5, jLabel7, jLabel8, jLabel9});

    panelLayout.setVerticalGroup(
      panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelLayout.createSequentialGroup()
        .addGap(38, 38, 38)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addGroup(panelLayout.createSequentialGroup()
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
            .addGap(6, 6, 6)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
            .addGap(4, 4, 4)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
            .addGap(6, 6, 6)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
          .addGroup(panelLayout.createSequentialGroup()
            .addComponent(lb_totalEarn, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
            .addGap(6, 6, 6)
            .addComponent(lb_total_owner, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
            .addGap(4, 4, 4)
            .addComponent(lb_total_married, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
            .addGap(6, 6, 6)
            .addComponent(lb_totalEarn3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
        .addGap(18, 18, 18)
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lb_owner_needed, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(1, 1, 1)
        .addComponent(lb_owner_neededExp, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lb_married_needed, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lb_married_neededExp)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel9)
          .addComponent(lb_total_needed))
        .addGap(27, 27, 27)
        .addComponent(jLabel10)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel11)
          .addComponent(lb_owner_ratio))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lb_owner_ratioExp)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel12)
          .addComponent(lb_married_ratio))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lb_married_ratioExp)
        .addGap(18, 18, 18)
        .addComponent(lb_foros, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel14)
          .addComponent(lb_owner_tax))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lb_owner_taxExp)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel15)
          .addComponent(lb_married_tax))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lb_married_taxExp)
        .addGap(7, 7, 7)
        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lb_totalForos)
          .addComponent(lb_total_tax))
        .addGap(41, 41, 41))
    );

    jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+2));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Υπολογισμός φόρου");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1))
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(6, 6, 6)
        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Main.glassPane.deactivate();
    dispose();
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    PrintUtilities.printComponent(panel);
  }//GEN-LAST:event_jButton2ActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel lb_foros;
  private javax.swing.JLabel lb_married_needed;
  private javax.swing.JLabel lb_married_neededExp;
  private javax.swing.JLabel lb_married_ratio;
  private javax.swing.JLabel lb_married_ratioExp;
  private javax.swing.JLabel lb_married_tax;
  private javax.swing.JLabel lb_married_taxExp;
  private javax.swing.JLabel lb_owner_needed;
  private javax.swing.JLabel lb_owner_neededExp;
  private javax.swing.JLabel lb_owner_ratio;
  private javax.swing.JLabel lb_owner_ratioExp;
  private javax.swing.JLabel lb_owner_tax;
  private javax.swing.JLabel lb_owner_taxExp;
  private javax.swing.JLabel lb_totalEarn;
  private javax.swing.JLabel lb_totalEarn3;
  private javax.swing.JLabel lb_totalForos;
  private javax.swing.JLabel lb_total_married;
  private javax.swing.JLabel lb_total_needed;
  private javax.swing.JLabel lb_total_owner;
  private javax.swing.JLabel lb_total_tax;
  private javax.swing.JPanel panel;
  // End of variables declaration//GEN-END:variables

  private void calculate() {
    calcOwnerNeeded();
    calcMarriedNeeded();
    totalNeeded = ownerNeeded + marriedNeeded;
    calcOwnerRatio();
    calcMarriedRatio();
    calcOwnerTax();
    calcMarriedTax();
    calcTotalTax();
  }

  private void calcOwnerTax() {
    ownerTax = (ownerRatio - ownerNeeded)*10/100;
    ownerTaxExp = "(" +Helper.convertAmountForViewing(ownerRatio) +" - " +
        Helper.convertAmountForViewing(ownerNeeded) + ") x 10%";
  }

  private void calcMarriedTax() {
    marriedTax = (marriedRatio - marriedNeeded)*10/100;
    marriedTaxExp = "(" +Helper.convertAmountForViewing(marriedRatio) +" - " +
        Helper.convertAmountForViewing(marriedNeeded) + ") x 10%";
  }

    private void calcOwnerNeeded() {
    Object[] c = calcNeeded(owner);
    ownerNeeded = (Double) c[0];
    ownerNeededExpl = (String) c[1];
  }

  private void calcMarriedNeeded() {
    Object[] c = calcNeeded(married);
    marriedNeeded = (Double) c[0];
    marriedNeededExpl = (String) c[1];
  }

  private void calcOwnerRatio() {
    Object[] c = calcRatio(owner);
    ownerRatio = (Double) c[0];
    ownerRatioExpl = (String) c[1];
  }

  private void calcMarriedRatio() {
    Object[] c = calcRatio(married);
    marriedRatio = (Double) c[0];
    marriedRatioExpl = (String) c[1];
  }

  private Object[] calcRatio(double amount) {
    double t = total * (amount / (owner + married));
    String e = Helper.convertAmountForViewing(total) + " x ("
        + Helper.convertAmountForViewing(amount) + "/("
        + Helper.convertAmountForViewing(owner) + " +"
        + Helper.convertAmountForViewing(married) + "))";

    return new Object[]{t, e};
  }

  private Object[] calcNeeded(double amount) {
    if (amount <= 6000) {
      return new Object[]{0.0, "Δεν απαιτούνται"};
    } else if (amount > 48000) {
      return new Object[]{12000.0, "Μεγιστο ποσό για εισοδήματα > " + 48000};
    } else {
      double tenPerCent = 12000 * 10 / 100;
      double thirtyPerCent = (amount - 12000) * 30 / 100;
      double tot = tenPerCent + thirtyPerCent;
      String ex = "("
          + Helper.convertAmountForViewing(12000) + " x 10% + "
          + (Helper.convertAmountForViewing(amount - 12000)) + " x 30% = "
          + Helper.convertAmountForViewing(tenPerCent + thirtyPerCent) + ")";
      return new Object[]{tot, ex};
    }
  }

  private void calcTotalTax() {
    totalTax = ownerTax + marriedTax;
    if(totalTax < 0){
      taxResult = "Επιβάρυνση φόρου";
      totalForosResult = "Συνολική επιβάρυνση φόρου:";
    } else {
      taxResult = "Ωφέλεια φόρου";
      totalForosResult = "Συνολική ωφέλεια φόρου:";
    }
  }
}
