/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Graph.java
 *
 * Created on 14 Φεβ 2011, 11:28:45 πμ
 */
package panels;

import components.MyDraggable;
import java.awt.Dimension;
import java.util.Iterator;
import java.util.Vector;
import models.Statistics;
import models.Statistics.KindStats;
import models.Statistics.MonthlyStats;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import receipts.Main;
import tools.Helper;

/**
 *
 * @author ssoldatos
 */
public class Graph extends MyDraggable {

  private static final long serialVersionUID = 45675756786L;
  private String[] names;
  private Vector<Object> collection;
  private int type;

  /** Creates new form Graph */
  public Graph() {
  }

  Graph(String[] names, Vector<Object> collection, int type) {
    this.names = names;
    this.collection = collection;
    this.type = type;
    Main.glassPane.activate(null);
    initComponents();
    createChart();
    setPreferredSize(new Dimension(400, 300));
    setLocationRelativeTo(null);
    setVisible(true);



  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panel = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    chartPanel = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

    panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

    jButton1.setText("Κλείσιμο");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    chartPanel.setMinimumSize(new java.awt.Dimension(600, 400));

    javax.swing.GroupLayout chartPanelLayout = new javax.swing.GroupLayout(chartPanel);
    chartPanel.setLayout(chartPanelLayout);
    chartPanelLayout.setHorizontalGroup(
      chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 890, Short.MAX_VALUE)
    );
    chartPanelLayout.setVerticalGroup(
      chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 508, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
    panel.setLayout(panelLayout);
    panelLayout.setHorizontalGroup(
      panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(chartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(panelLayout.createSequentialGroup()
        .addComponent(jButton1)
        .addContainerGap(819, Short.MAX_VALUE))
    );
    panelLayout.setVerticalGroup(
      panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelLayout.createSequentialGroup()
        .addComponent(chartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton1))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Main.glassPane.deactivate();
    dispose();
  }//GEN-LAST:event_jButton1ActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel chartPanel;
  private javax.swing.JButton jButton1;
  private javax.swing.JPanel panel;
  // End of variables declaration//GEN-END:variables

  private void createChart() {
    DefaultPieDataset dataset = new DefaultPieDataset();
    KindStats kcol;
    MonthlyStats mcol;

    for (Iterator<Object> it = collection.iterator(); it.hasNext();) {
      Object col = it.next();
      String desc = "";
      Double val = 0.0;
      if (type==Statistics.KIND) {
        kcol = (KindStats) col;
        desc = kcol.description;
        val = kcol.amount;

      } else if (type==Statistics.MONTHLY){
        mcol = (MonthlyStats) col;
        desc = Helper.getGreekMonth(mcol.month);
        val = mcol.amount;
      }
      dataset.setValue(desc, val);
    }
    JFreeChart chart = ChartFactory.createPieChart(
        "Στατισικά ανά είδος", // chart title
        dataset, // data
        true, // include legend
        true,
        false);

    ChartPanel cpanel = new ChartPanel(chart);
    cpanel.setSize(chartPanel.getSize());
    chartPanel.add(cpanel);
    chartPanel.getParent().validate();






  }
}
