/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TypoesPanel.java
 *
 * Created on 16 Ιαν 2010, 12:05:59 μμ
 */
package components;

import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author lordovol
 */
public abstract class MyStaticTablePanel extends javax.swing.JPanel {

  protected int rowSelected;
  protected int colSelected;
  protected String title = "";
  protected String hint = "";
  protected MyTableModel tableModel;
  protected static Object object;
  protected int colNumber;
  protected int _NUMBER_OF_FIELDS;
  protected String _TABLE_NAME_;
  protected String _KIND_STATISTICS_ = "Kind statistics";
  protected String _MONTHLY_STATISTICS_ = "Monthly statistics";
  protected String _RECEIPTS_ = "Receipts";


  public MyStaticTablePanel() {
    //initComponents();
  }

  protected void init() {
    initComponents();
  }

  public void setTitle(String title) {
    label_title.setText(title);
  }

  public void setHint(String hint) {
    label_hint.setText(hint);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    scrollPane_table = new javax.swing.JScrollPane();
    table = new javax.swing.JTable();
    label_title = new javax.swing.JLabel();
    label_hint = new javax.swing.JLabel();
    label_hint2 = new javax.swing.JLabel();
    bt_popup = new javax.swing.JButton();

    table.setAutoCreateRowSorter(true);
    table.setModel(tableModel);
    table.setOpaque(false);
    table.setRowHeight(20);
    scrollPane_table.setViewportView(table);

    label_title.setFont(label_title.getFont().deriveFont(label_title.getFont().getStyle() | java.awt.Font.BOLD, label_title.getFont().getSize()+2));
    label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    label_title.setText(title);

    label_hint.setText(hint);

    label_hint2.setForeground(Color.BLUE);
    label_hint2.setText(hint);

    bt_popup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pie_chart.png"))); // NOI18N
    bt_popup.setBorder(null);
    bt_popup.setBorderPainted(false);
    bt_popup.setContentAreaFilled(false);
    bt_popup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(label_hint, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
              .addComponent(scrollPane_table, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
              .addComponent(label_hint2, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
              .addComponent(label_title, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
          .addComponent(bt_popup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(bt_popup, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGap(11, 11, 11)
            .addComponent(label_title)))
        .addGap(10, 10, 10)
        .addComponent(scrollPane_table, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(label_hint)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(label_hint2)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  protected void addColumns(String[] names, int[] pref, int[] min, int[] max) {

    colNumber = names.length;
    for (int i = 0; i < colNumber; i++) {
      tableModel.addColumn(names[i]);
      table.getTableHeader().getColumnModel().getColumn(i).setPreferredWidth(pref[i]);
      table.getTableHeader().getColumnModel().getColumn(i).setMaxWidth(max[i]);
      table.getTableHeader().getColumnModel().getColumn(i).setMinWidth(min[i]);
    }


  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  protected javax.swing.JButton bt_popup;
  private javax.swing.JLabel label_hint;
  private javax.swing.JLabel label_hint2;
  private javax.swing.JLabel label_title;
  private javax.swing.JScrollPane scrollPane_table;
  protected javax.swing.JTable table;
  // End of variables declaration//GEN-END:variables


  /**
   * @param secondHint the secondHint to set
   */
  public void setSecondHint(String secondHint) {
    label_hint2.setText(secondHint);
  }
}


