/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DBPanel.java
 *
 * Created on 18 Φεβ 2011, 9:10:31 πμ
 */
package tools.options;

import components.Database;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ssoldatos
 */
public class GeneralPanel extends javax.swing.JPanel {

  private static final long serialVersionUID = 34536346456L;
  DefaultComboBoxModel dbmodel = new DefaultComboBoxModel();

  /** Creates new form DBPanel */
  public GeneralPanel() {
    dbmodel = new DefaultComboBoxModel(Database.getDatabases());
    dbmodel.insertElementAt(Options.ASK_FOR_DB, 0);
    initComponents();
    
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();

    setBackground(new java.awt.Color(255, 255, 255));

    jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+2));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Γενικές Ρυθμίσεις");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addContainerGap(157, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
